import smtplib

from email.mime.text import MIMEText


print("===== USING ROOT EMAIL ALERT FILE =====")


def send_alert_email(aqi, category, receiver_email):

    print("========== EMAIL FUNCTION STARTED ==========")
    print("Receiver:", receiver_email)
    print("AQI:", aqi)
    print("Category:", category)

    sender_email = "anshika.tiwari1829@gmail.com"
    sender_password = "cfxjixpgzrtnyhgw"

    subject = f"AQI Alert - {category}"

    body = f"""
Air Quality Alert

Predicted AQI : {aqi}

Category : {category}

Please take necessary precautions.

Generated by:
Air Quality Prediction and Monitoring System
"""

    msg = MIMEText(body)

    msg["Subject"] = subject
    msg["From"] = sender_email
    msg["To"] = receiver_email

    try:

        print("Connecting to Gmail SMTP...")

        server = smtplib.SMTP(
            "smtp.gmail.com",
            587,
            timeout=30
        )

        print("Connected Successfully")

        print("Starting TLS...")

        server.starttls()

        print("TLS Started")

        print("Logging into Gmail...")

        server.login(
            sender_email,
            sender_password
        )

        print("LOGIN SUCCESS")

        print("Sending Email...")

        server.sendmail(
            sender_email,
            receiver_email,
            msg.as_string()
        )

        print("EMAIL SENT SUCCESSFULLY")

        server.quit()

        print("SMTP Connection Closed")

        return {
            "status": "success",
            "message": "Email Sent Successfully"
        }

    except Exception as e:

        print("========== SMTP ERROR ==========")
        print(type(e).__name__)
        print(str(e))
        print("===============================")

        raise Exception(str(e))