import smtplib
from email.mime.text import MIMEText


def send_alert_email(aqi, category, receiver_email):

    sender_email = "anshika.tiwari1829@gmail.com"
    sender_password = "cfxjixpgzrtnyhgw"

    subject = f"AQI Alert - {category}"

    body = f"""
Air Quality Alert

Predicted AQI: {aqi}

Category: {category}

Please take necessary precautions.

Generated by:
Air Quality Prediction and Monitoring System
"""

    msg = MIMEText(body)

    msg["Subject"] = subject
    msg["From"] = sender_email
    msg["To"] = receiver_email

    try:

        server = smtplib.SMTP(
            "smtp.gmail.com",
            587
        )

        server.starttls()

        server.login(
            sender_email,
            sender_password
        )

        server.sendmail(
            sender_email,
            receiver_email,
            msg.as_string()
        )

        server.quit()

        print("Alert Email Sent Successfully")

    except Exception as e:

        print("Email Error:", e)