import os
import smtplib

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


def send_alert_email(aqi, category, receiver_email):

    sender_email = os.getenv("ALERT_EMAIL")
    app_password = os.getenv("EMAIL_PASS")

    if not sender_email:
        raise Exception(
            "ALERT_EMAIL environment variable not found."
        )

    if not app_password:
        raise Exception(
            "EMAIL_PASS environment variable not found."
        )

    try:

        subject = f"AQI Alert - {category}"

        html_body = f"""
        <html>
        <body>

        <h2>🌍 Air Quality Alert</h2>

        <p><b>Predicted AQI:</b> {aqi}</p>

        <p><b>Category:</b> {category}</p>

        <p>
        Please take necessary precautions based on the current
        air quality conditions.
        </p>

        <hr>

        <p>
        Generated by Air Quality Prediction and Monitoring System
        </p>

        </body>
        </html>
        """

        message = MIMEMultipart()
        message["From"] = sender_email
        message["To"] = receiver_email
        message["Subject"] = subject

        message.attach(
            MIMEText(html_body, "html")
        )

        server = smtplib.SMTP(
            "smtp.gmail.com",
            587
        )

        server.starttls()

        server.login(
            sender_email,
            app_password
        )

        server.sendmail(
            sender_email,
            receiver_email,
            message.as_string()
        )

        server.quit()

        print("========== SMTP DEBUG ==========")
        print("Email sent successfully")
        print("To:", receiver_email)
        print("AQI:", aqi)
        print("Category:", category)
        print("================================")

        return {
            "status": "success",
            "message": "Email sent successfully"
        }

    except Exception as e:

        print("========== SMTP ERROR ==========")
        print(str(e))
        print("================================")

        raise Exception(
            f"Failed to send email: {str(e)}"
        )