import os
import requests


def send_alert_email(aqi, category, receiver_email):

    api_key = os.getenv("RESEND_API_KEY")
    sender_email = os.getenv("ALERT_EMAIL")

    if not api_key:
        raise Exception(
            "RESEND_API_KEY environment variable not found."
        )

    if not sender_email:
        raise Exception(
            "ALERT_EMAIL environment variable not found."
        )

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    payload = {
        "from": f"AQI Alert <{sender_email}>",
        "to": [receiver_email],
        "subject": f"AQI Alert - {category}",
        "html": f"""
        <h2>🌍 Air Quality Alert</h2>

        <p><b>Predicted AQI:</b> {aqi}</p>

        <p><b>Category:</b> {category}</p>

        <p>
        Please take necessary precautions based on the current
        air quality conditions.
        </p>

        <hr>

        <p>
        Generated by Air Quality Prediction and Monitoring System
        </p>
        """,
    }

    try:

        response = requests.post(
            "https://api.resend.com/emails",
            headers=headers,
            json=payload,
            timeout=30,
        )

        print("========== RESEND DEBUG ==========")
        print("Status Code:", response.status_code)
        print("Response:", response.text)
        print("==================================")

        if response.status_code not in [200, 201]:

            raise Exception(
                f"Resend API Error: {response.text}"
            )

        print(
            f"Email successfully sent to {receiver_email}"
        )

        return response.json()

    except Exception as e:

        print(
            f"Email sending failed: {str(e)}"
        )

        raise Exception(
            f"Failed to send email: {str(e)}"
        )