import requests
import os


def send_alert_email(aqi, category, receiver_email):

    api_key = os.getenv("RESEND_API_KEY")

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    payload = {
        "from": "AQI Alert <onboarding@resend.dev>",
        "to": [receiver_email],
        "subject": f"AQI Alert - {category}",
        "html": f"""
        <h2>Air Quality Alert</h2>

        <p><b>Predicted AQI:</b> {aqi}</p>

        <p><b>Category:</b> {category}</p>

        <p>Please take necessary precautions.</p>

        <hr>

        <p>Generated by Air Quality Prediction and Monitoring System</p>
        """
    }

    response = requests.post(
        "https://api.resend.com/emails",
        headers=headers,
        json=payload
    )

    if response.status_code not in [200, 201]:
        raise Exception(response.text)